<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Thomas Petzoldt">
  <meta name="dcterms.date" content="2025-11-22">
  <title>Elemente der statistischen Datenanalyse und Statistik mit R – 05-Klassische Tests</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-cb13c09ad5a7270edb89df8c4c84031f.css">
  <link rel="stylesheet" href="../thpe.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
  #title-slide 
    .title {color: #cef0ffff;}
    .subtitle {color: #ee7f00;}
    .quarto-title-author {color: #69af22;}
    .date {color: #69af22;}
  </style>  
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" body-color="#ffffff" data-background-image="../img/tud-title-bg-wide-2021.png" class="quarto-title-block center">
  <h1 class="title">05-Klassische Tests</h1>
  <p class="subtitle">Angewandte Statistik – Ein Praxiskurs</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Thomas Petzoldt 
</div>
</div>
</div>

  <p class="date">2025-11-22</p>
</section>
<section>
<section id="hypothesen-fehler-und-der-p-wert" class="title-slide slide level1 center">
<h1>Hypothesen, Fehler und der p-Wert</h1>
<!--
ToDo: insert formulae and algorithms from the slides
-->
</section>
<section id="statistische-tests" class="slide level2">
<h2>Statistische Tests</h2>
<p><br></p>
<p>Ein statistischer Test hilft zu entscheiden, ob eine Hypothese wahrscheinlich richtig ist oder nicht, basierend auf vorliegenden Daten.</p>
<ul>
<li>Beispiel: Wir vergleichen zwei Stichproben oder eine Stichprobe mit einem statistischen Modell.</li>
<li>Dazu stellen zwei Hypothesen auf:
<ul>
<li><strong>Alternativhypothese</strong> (<span class="math inline">\(H_a\)</span>): Das ist unsere eigentliche Hypothese, dass es einen Unterschied oder eine Beziehung gibt.</li>
<li><strong>Nullhypothese</strong> (<span class="math inline">\(H_0\)</span>): Wir nehmen an, dass es keinen Unterschied oder keine Beziehung gibt und testen, ob wir diese Hypothese ablehnen können.</li>
</ul></li>
<li><strong>Statistisch signifikant</strong> bedeutet: Die Wahrscheinlichkeit, dass wir unsere Beobachtung nur durch puren Zufall gemacht haben, ist sehr gering. Wenn das so ist, sagen wir, dass unser Ergebnis signifikant ist und <span class="math inline">\(H_a\)</span> unterstützt wird.</li>
</ul>
<p>siehe dazu auch: <a href="https://de.wikipedia.org/wiki/Statistischer_Test">https://de.wikipedia.org/wiki/Statistischer_Test</a></p>
</section>
<section id="effektstärke-und-signifikanz" class="slide level2">
<h2>Effektstärke und Signifikanz</h2>
<p><br></p>
<p>Für Mittelwertdifferenzen ist die relative Effektstärke:</p>
<div class="bigfont">
<p><span class="math display">\[
  \delta = \frac{\bar{\mu}_1-\bar{\mu}_2}{\sigma}=\frac{\Delta}{\sigma}
\]</span></p>
</div>
<p>mit:</p>
<ul>
<li>Mittelwerte von zwei Grundgesamtheiten <span class="math inline">\(\mu_1, \mu_2\)</span></li>
<li>absolute Effektstärke <span class="math inline">\(\Delta\)</span></li>
<li>relative Effektstärke <span class="math inline">\(\delta\)</span> (auch Cohen’s d genannt)</li>
<li><strong>Signifikanz</strong> bedeutet, dass es unwahrscheinlich ist, dass ein beobachteter Effekt das Ergebnis einer reinen Zufallsvariation ist.</li>
</ul>
</section>
<section id="nullhypothese-und-alternativhypothese" class="slide level2">
<h2>Nullhypothese und Alternativhypothese</h2>
<p><br></p>
<p><span class="blue"><strong><span class="math inline">\(H_0\)</span></strong></span> Nullhypothese: Zwei Grundgesamtheiten unterscheiden sich nicht in Bezug auf eine bestimmte Eigenschaft.</p>
<ul>
<li>Annahme: Der beobachtete Effekt ist rein zufällig entstanden, der wahre Effekt ist Null.</li>
</ul>
<p><span class="darkred"><strong><span class="math inline">\(H_a\)</span></strong></span> Alternativhypothese (Versuchshypothese): Vorhandensein eines bestimmten Effekts.</p>
<ul>
<li>Eine Alternativhypothese ist nie vollständig wahr oder „bewiesen“.</li>
<li>Die Annahme von <span class="math inline">\(H_A\)</span> bedeutet nur, dass <span class="math inline">\(H_0\)</span> unwahrscheinlich ist.</li>
</ul>
<p><strong>„Nicht signifikant“ bedeutet entweder kein Effekt oder Stichprobengröße zu klein!</strong></p>
<p><br></p>
<p><span class="blue">Anmerkung: Unterschiedliche Bedeutung von <strong>Signifikanz</strong> (<span class="math inline">\(H_0\)</span> unwahrscheinlich) und <strong>Relevanz</strong> (Effekt groß genug, um in der Praxis eine Rolle zu spielen).</span></p>
</section>
<section id="der-p-wert" class="slide level2">
<h2>Der p-Wert</h2>
<p><br></p>
<p>Die Interpretation des p-Wertes war in der Vergangenheit oft verwirrend, selbst in Statistik-Lehrbüchern, so dass es gut ist, sich auf eine klare Definition zu beziehen:</p>
<div class="bigfont">
<blockquote>
<p>Der p-Wert ist definiert als die Wahrscheinlichkeit, ein Ergebnis zu erhalten, das gleich oder „extremer“ ist als das, was tatsächlich beobachtet wurde, wenn die Nullhypothese wahr ist.</p>
</blockquote>
</div>
<p><br></p>
<ul>
<li><p><a href="https://en.wikipedia.org/wiki/P-value">https://en.wikipedia.org/wiki/P-value</a>:</p></li>
<li><p><span class="citation" data-cites="hubbard_alphabet_2004">Hubbard (<a href="#/literatur" role="doc-biblioref" onclick="">2004</a>)</span> Alphabet Soup: Blurring the Distinctions Between p’s and a’s in Psychological Research, Theory Psychology 14(3), 295-327. DOI: <a href="https://doi.org/10.1177/0959354304043638">10.1177/0959354304043638</a></p></li>
</ul>
</section>
<section id="alpha--und-beta-fehler" class="slide level2">
<h2>Alpha- und Beta-Fehler</h2>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 30%">
<col style="width: 12%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Realität</th>
<th style="text-align: center;">Entscheidung des Tests</th>
<th style="text-align: center;">Richtig?</th>
<th style="text-align: center;">Wahrscheinlichkeit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(H_0\)</span> = wahr</td>
<td style="text-align: center;">signifikant</td>
<td style="text-align: center;">nein</td>
<td style="text-align: center;"><span class="math inline">\(\alpha\)</span>-Fehler</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(H_0\)</span> = falsch</td>
<td style="text-align: center;">nicht signifikant</td>
<td style="text-align: center;">nein</td>
<td style="text-align: center;"><span class="math inline">\(\beta\)</span>-Fehler</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(H_0\)</span> = wahr</td>
<td style="text-align: center;">nicht signifikant</td>
<td style="text-align: center;">ja</td>
<td style="text-align: center;"><span class="math inline">\(1-\alpha\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(H_0\)</span> = falsch</td>
<td style="text-align: center;">signifikant</td>
<td style="text-align: center;">ja</td>
<td style="text-align: center;"><span class="math inline">\(1-\beta\)</span> (Trennschärfe)</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>1.<span class="math inline">\(H_0\)</span> fälschlicherweise abgelehnt (Fehler erster Art oder <span class="math inline">\(\alpha\)</span>-Fehler)</p>
<ul>
<li>es wird ein Effekt behauptet, den es nicht gibt, z.B. ein Medikament, das keine Wirkung hat</li>
</ul>
<p>2.<span class="math inline">\(H_0\)</span> fälschlicherweise beibehalten (Fehler zweiter Art oder <span class="math inline">\(\beta\)</span>-Fehler)</p>
<ul>
<li>typischer Fall in kleinen Studien, bei denen die Wirkung nicht ausreicht, um vorhandene Effekte zu erkennen</li>
</ul>
<p><strong>Verwendung in der Praxis</strong></p>
<ul>
<li>übliche Konvention in den Umweltwissenschaften: <span class="math inline">\(\alpha=0.05\)</span>, muss vorher festgelegt werden</li>
<li><span class="math inline">\(\beta=f(\alpha, \text{Effektstärke}, \text{Stichprobengröße},
\text{Art des Tests})\)</span>, sollte <span class="math inline">\(\le 0.2\)</span> sein</li>
</ul>
</section>
<section id="signifikanz-und-relevanz" class="slide level2">
<h2>Signifikanz und Relevanz</h2>
<p><br></p>
<ul>
<li><p>Statistische <strong>Signifikanz</strong>: die Nullhypothese <span class="math inline">\(H_0\)</span> ist im statistischen Sinne unwahrscheinlich.</p></li>
<li><p>Praktische <strong>Relevanz</strong> (manchmal auch „praktische Signifikanz“ genannt): die Effektstärke ist groß genug, um in der Praxis eine Rolle zu spielen.</p></li>
</ul>
<p>Ob ein Effekt relevant sein kann oder nicht, hängt also von seiner <strong>Effektstärke</strong> und dem Anwendungsbereich ab.</p>
<p>Betrachten wir zum Beispiel eine Impfung. Wenn ein Impfstoff in einem klinischen Test eine signifikante Wirkung hat, aber nur 10 von 1000 Menschen schützt, würde man diesen Effekt nicht als relevant ansehen und diesen Impfstoff nicht herstellen.</p>
<p>Andererseits können auch kleine Wirkungen von Bedeutung sein. Wenn also eine toxische Substanz bei 1 von 1000 Personen Krebs auslösen würde, würden wir das als relevant betrachten. Um es auch als signifikant zu erkennen, ist eine epidemiologische Studie mit einer großen Anzahl von Menschen erforderlich. Da es sich aber um eine hochrelevante Wirkung handelt, lohnt sich der Aufwand.</p>
</section>
<section id="take-home-messages" class="slide level2">
<h2>Take home messages</h2>
<ul>
<li><p>Ein p-Wert misst die Wahrscheinlichkeit, dass ein rein zufälliger Effekt gleich groß oder größer ist als ein beobachteter Effekt, <strong>wenn die Nullhypothese wahr ist</strong>.</p></li>
<li><p><strong>Signifikant</strong>, die Ergebnisse sind unwahrscheinlich, wenn es keinen echten Effekt gäbe.</p></li>
<li><p><strong>Nicht signifikant</strong> bedeutet nicht „kein Effekt“.</p></li>
<li><p>Nicht signifikante Ergebnisse deuten auf die Notwendigkeit weiterer Untersuchungen hin:</p>
<ul>
<li>Vergrößerung der Stichprobe</li>
<li>Erhöhung des experimentellen Effekts</li>
<li>Reduzierung des experimentellen Fehlers</li>
<li>Wahl eines leistungsfähigeren statistischen Verfahrens</li>
</ul></li>
<li><p>Wichtig: Konzentriere Dich nicht nur auf p-Werte und Signifikanz!</p></li>
<li><p>Vergiss nie, Stichprobengröße, <strong>Effektstärke</strong> und Relevanz anzugeben.</p></li>
<li><p>Bei großen Datensätzen:</p>
<ul>
<li>Statistisch signifikante Ergebnisse können leicht auch für sehr kleine und praktisch irrelevante Effekte erzielt werden.</li>
<li><span class="math inline">\(\rightarrow\)</span> Effektstärke und Relevanz werden wichtiger als p-Werte.</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="differenzen-zwischen-mittelwerten" class="title-slide slide level1 center">
<h1>Differenzen zwischen Mittelwerten</h1>

</section>
<section id="einstichproben-t-test" class="slide level2">
<h2>Einstichproben-t-Test</h2>
<p><br></p>
<ul>
<li>prüft, ob eine Stichprobe aus einer Grundgesamtheit mit gegebenem Mittelwert <span class="math inline">\(\mu\)</span> stammt</li>
<li>basiert auf der Prüfung, ob der Mittelwert der Grundgesamtheit <span class="math inline">\(\mu\)</span> im Konfidenzintervall von <span class="math inline">\(\bar{x}\)</span> liegt</li>
</ul>
<ol type="1">
<li>Angenommen, wir haben eine Stichprobe mit dem Umfang <span class="math inline">\(n=10, \bar{x}=5.5, s=1\)</span> und <span class="math inline">\(\mu=5\)</span>.</li>
<li>Nun schätzen wir das 95%-Konfidenzintervall von <span class="math inline">\(\bar{x}\)</span>:</li>
</ol>
<p><span class="math display">\[
CI = \bar{x} \pm t_{1-\alpha/2, n-1} \cdot s_{\bar{x}}
\]</span> mit <span class="math display">\[
s_{\bar{x}} = \frac{s}{\sqrt{n}} \qquad \text{(Standardfehler)}
\]</span></p>
<p>Auf den folgenden Folien werden unterschiedliche Berechnungsmethoden vorgestellt.</p>
</section>
<section id="zur-erinnerung-standardabweichung-und-standardfehler" class="slide level2">
<h2>Zur Erinnerung: Standardabweichung und Standardfehler</h2>

<img data-src="05-classtests_files/figure-revealjs/sd-and-se-1.png" width="960" class="r-stretch"><p><small> Visualisierung eines Einstichproben-t-Test. Links: ursprüngliche Verteilung der Daten, gemessen an der Standardabweichung, rechts: Verteilung der Mittelwerte, gemessen an ihrem Standardfehler. </small></p>
<p><span class="math display">\[
s_{\bar{x}} = \frac{s}{\sqrt{n}} \qquad \text{(Standardfehler)}
\]</span></p>
<ul>
<li>Standardfehler &lt; Standardabweichung</li>
<li>misst die Genauigkeit des Mittelwerts</li>
<li>ZGWS!</li>
</ul>
<p>Wichtig: Der Test arbeitet mit der Verteilung der Mittelwerte, nicht mit der Verteilung der ursprünglichen Daten.</p>
</section>
<section id="methode-1-liegt-mu-im-konfidenzintervall" class="slide level2">
<h2>Methode 1: Liegt <span class="math inline">\(\mu\)</span> im Konfidenzintervall?</h2>
<p><br></p>
<ol type="1">
<li><p>Stichprobe: <span class="math inline">\(n=10, \bar{x}=5.5, s=1\)</span> und <span class="math inline">\(\mu=5\)</span></p></li>
<li><p>Wenn <span class="math inline">\(\alpha = 0,05\)</span> ist, erhalten wir ein zweiseitiges 95%-Konfidenzintervall mit:</p></li>
</ol>
<p><span class="math display">\[\bar{x} \pm t_{0,975, n-1} \cdot \frac{s}{\sqrt{n}}\]</span></p>
<div class="bigfont">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fl">5.5</span> <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">10-1</span>) <span class="sc">*</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.784643 6.215357</code></pre>
</div>
</div>
</div>
<p><br></p>
<ol start="3" type="1">
<li><p>Prüfung, ob <span class="math inline">\(\mu=5.0\)</span> in diesem Intervall liegt?</p></li>
<li><p>Ja, es befindet sich innerhalb <span class="math inline">\(\Rightarrow\)</span> <span class="blue">Unterschied nicht signifikant</span>.</p></li>
</ol>
</section>
<section id="methode-2-vergleich-mit-einem-tabellierten-t-wert" class="slide level2">
<h2>Methode 2: Vergleich mit einem tabellierten t-Wert</h2>
<ol type="1">
<li>Umstellung der Gleichung des Konfidenzintervalls, Berechnung eines beobachteten <span class="math inline">\(t\)</span>-Werts, <span class="math inline">\(t_{obs}\)</span>:</li>
</ol>
<p><span class="math display">\[
t_{obs} = |\bar{x}-\mu | \cdot \frac{1}{s_{\bar{x}}} = \frac{|\bar{x}-\mu |}{s} \cdot \sqrt{n} = \frac{|5.5 -5.0|}{1.0} \cdot \sqrt{10}
\]</span></p>
<p>Berechnung in <strong>R</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fl">5.5</span> <span class="sc">-</span> <span class="fl">5.0</span>) <span class="sc">/</span> <span class="fl">1.0</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">10</span>)</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.581139</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Vergleich von <span class="math inline">\(t_{obs}\)</span> mit einem tabellierten Wert</li>
</ol>
<ul>
<li>„Historische Methode“: Ablesen des kritischen t-Wertes für gegebenes <span class="math inline">\(\alpha\)</span> und Freiheitsgrade (<span class="math inline">\(n-1\)</span>) aus einer Tabelle.</li>
<li>Für <span class="math inline">\(\alpha=0.05\)</span> und zweiseitig ist das: <span class="math inline">\(t_{1-\alpha/2, n-1} = 2.26\)</span>.</li>
</ul>
<p>Vergleich: <span class="math inline">\(1.58 &lt; 2.26\)</span> <span class="math inline">\(\Rightarrow\)</span> kein signifikanter Unterschied zwischen <span class="math inline">\(\bar{x}\)</span> und <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="methode-3-berechnung-des-p-wertes-aus-t_obs" class="slide level2">
<h2>Methode 3: Berechnung des p-Wertes aus <span class="math inline">\(t_{obs}\)</span></h2>
<p><br></p>
<ul>
<li>Verwendung der computergestützten Wahrscheinlichkeitsfunktion der t-Verteilung (<code>pt</code>) anstelle des Tabellenvergleichs</li>
<li>Für <span class="math inline">\(t = t_{obs}\)</span> und Anzahl der Freiheitsgrade (<span class="math inline">\(n-1\)</span>):</li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(t, <span class="at">df =</span> <span class="dv">10</span> <span class="sc">-</span> <span class="dv">1</span>)) <span class="co"># 2 * (1 - p) ist umgestellt von 1-alpha/2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1483047</code></pre>
</div>
</div>
<p>Der p-Wert = 0.1483047 ist größer als <span class="math inline">\(0,05\)</span>, somit betrachten wir die Differenz als nicht signifikant.</p>
<p><br></p>
<p><strong>FAQ: kleiner oder größer als?</strong></p>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 35%">
<col style="width: 34%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>p-Wert</td>
<td><span class="math inline">\(\text{p-Wert} &lt; \alpha\)</span></td>
<td>Nullhypothese unwahrscheinlich</td>
<td>signifikant</td>
</tr>
<tr class="even">
<td>Test Statistik</td>
<td><span class="math inline">\(t_{obs} &gt; t_{1-\alpha/2, n-1}\)</span></td>
<td>Effekt übersteigt Grenze</td>
<td>signifikant</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="methode-4-integrierte-t-test-funktion-in-r" class="slide level2">
<h2>Methode 4: Integrierte t-Test-Funktion in R</h2>
<p><br></p>
<p>Das Gleiche kann man viel einfacher mit dem Computer in <strong>R</strong> machen.</p>
<p>Angenommen, wir haben eine Stichprobe mit <span class="math inline">\(\bar{x}=5, s=1\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-hidden="true" tabindex="-1"></a><span class="do">## definiere Stichprobe</span></span>
<span id="cb7-2"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.5</span>, <span class="fl">3.5</span>, <span class="fl">5.4</span>, <span class="fl">5.3</span>, <span class="dv">6</span>, <span class="fl">7.2</span>, <span class="fl">5.4</span>, <span class="fl">6.3</span>, <span class="fl">4.5</span>, <span class="fl">5.9</span>)</span>
<span id="cb7-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a aria-hidden="true" tabindex="-1"></a><span class="do">## führe Einstichproben-t-Test durch</span></span>
<span id="cb7-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  x
t = 1.5811, df = 9, p-value = 0.1483
alternative hypothesis: true mean is not equal to 5
95 percent confidence interval:
 4.784643 6.215357
sample estimates:
mean of x 
      5.5 </code></pre>
</div>
</div>
<p>Der Test liefert den beobachteten t-Wert, das 95%-Konfidenzintervall und den p-Wert.</p>
<p>Ein wichtiger Unterschied ist, dass diese Methode mit den Originaldaten arbeitet, während die anderen Methoden nur Mittelwert, Standardabweichung und Stichprobenumfang benötigen.</p>
</section>
<section id="zweistichproben-t-test" class="slide level2">
<h2>Zweistichproben-t-Test</h2>
<p><br></p>
<p>Der Zweistichproben-t-Test vergleicht zwei unabhängige Stichproben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.3</span>, <span class="fl">6.0</span>, <span class="fl">7.1</span>, <span class="fl">6.4</span>, <span class="fl">5.7</span>, <span class="fl">4.9</span>, <span class="fl">5.0</span>, <span class="fl">4.6</span>, <span class="fl">5.7</span>, <span class="fl">4.0</span>, <span class="fl">4.5</span>, <span class="fl">6.5</span>)</span>
<span id="cb9-2"><a aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.8</span>, <span class="fl">7.1</span>, <span class="fl">5.8</span>, <span class="fl">7.0</span>, <span class="fl">6.7</span>, <span class="fl">7.7</span>, <span class="fl">9.2</span>, <span class="fl">6.0</span>, <span class="fl">7.2</span>, <span class="fl">7.8</span>, <span class="fl">7.8</span>, <span class="fl">5.7</span>)</span>
<span id="cb9-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -3.7185, df = 21.611, p-value = 0.001224
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.3504462 -0.6662205
sample estimates:
mean of x mean of y 
 5.475000  6.983333 </code></pre>
</div>
</div>
<p><br></p>
<ul>
<li><span class="math inline">\(\rightarrow\)</span> beide Stichproben unterscheiden sich signifikant (<span class="math inline">\(p &lt; 0,05\)</span>)</li>
<li>Anmerkung: <strong>R</strong> hat hier nicht den „normalen“ t-Test durchgeführt, sondern den Welch-Test (= heteroskedastischer t-Test),</li>
<li>bei dem die Varianzen der beiden Stichproben nicht gleich sein müssen.</li>
</ul>
</section>
<section id="hypothese-und-formel-für-den-zweistichproben-t-test" class="slide level2">
<h2>Hypothese und Formel für den Zweistichproben-t-Test</h2>
<p><br></p>
<div class="column" style="width:49%;">
<p><span class="math inline">\(H_0\)</span> <span class="math inline">\(\mu_1 = \mu_2\)</span></p>
<p><span class="math inline">\(H_a\)</span> die beiden Mittelwerte sind unterschiedlich</p>
<p><strong>Testkriterium</strong></p>
<p><span class="math display">\[
t_{obs} =\frac{|\bar{x}_1-\bar{x}_2|}{s_{tot}} \cdot \sqrt{\frac{n_1 n_2}{n_1+n_2}}
\]</span></p>
</div><div class="column" style="width:49%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/twosample-t-test-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><p><strong>gepoolte Standardabweichung</strong></p>
<p><span class="math display">\[
s_{tot} = \sqrt{{({n}_1 - 1)\cdot s_1^2 + ({n}_2 - 1)\cdot s_2^2
\over ({n}_1 + {n}_2 - 2)}}
\]</span></p>
<p><strong>Annahmen:</strong> Unabhängigkeit, gleiche Varianzen, annähernde Normalverteilung</p>
</section>
<section id="der-welch-test" class="slide level2">
<h2>Der Welch-Test</h2>
<p><br></p>
<p><strong>Bekannt als t-Test für Stichproben mit ungleicher Varianz, funktioniert auch bei gleicher Varianz!</strong></p>
<p><br></p>
<p>Testkriterium:</p>
<p><span class="math display">\[
t = \frac{\bar{x}_1 - \bar{x}_2}{\sqrt{s^2_{\bar{x}_1} + s^2_{\bar{x}_2}}}
\]</span></p>
<p>Standardfehler der einzelnen Stichproben:</p>
<p><span class="math display">\[
s_{\bar{x}_i} = \frac{s_i}{\sqrt{n_i}}
\]</span> Korrigierte Freiheitsgrade:</p>
<p><span class="math display">\[
\text{df} = \frac{\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}}{\frac{s^4_1}{n^2_1(n_1-1)} + \frac{s^4_2}{n^2_2(n_2-1)}}
\]</span></p>
</section>
<section id="welch-test-in-r" class="slide level2">
<h2>Welch-Test in R</h2>
<p><br></p>
<div class="bigfont">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -3.7185, df = 21.611, p-value = 0.001224
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.3504462 -0.6662205
sample estimates:
mean of x mean of y 
 5.475000  6.983333 </code></pre>
</div>
</div>
</div>
<p>… das ist die Standardmethode der <code>t.test</code>-Funktion.</p>
</section>
<section id="test-auf-varianzgleichheit-f-test" class="slide level2">
<h2>Test auf Varianzgleichheit: F-Test</h2>
<div class="column" style="width:69%;">
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\sigma_1^2 = \sigma_2^2\)</span></p>
<p><span class="math inline">\(H_a\)</span>: Varianzen ungleich</p>
<p><strong>Testkriterium:</strong></p>
<p><span class="math display">\[F = \frac{s_1^2}{s_2^2} \]</span></p>
<ul>
<li>größere der beiden Varianzen im Zähler <span class="math inline">\((s^2_1 &gt; s^2_2)\)</span></li>
<li>Freiheitsgrade (<span class="math inline">\(n-1\)</span>) für Zähler und Nenner können verschieden sein</li>
</ul>
</div><div class="column" style="width:29%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/var-homogeneity-1.png" width="384"></p>
</figure>
</div>
</div>
</div>
</div><p><strong>Beispiel:</strong></p>
<ul>
<li><span class="red"><span class="math inline">\(s_1=1\)</span></span>, <span class="blue"><span class="math inline">\(s_2 =2\)</span></span>, <span class="math inline">\(n_1=5, n_2=10, F=\frac{2^2}{1^2}=4\)</span></li>
<li>Freiheitsgrad: <span class="math inline">\(9 \atop 4\)</span></li>
</ul>
<p><span class="darkred"><span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(F_{9, 4, \alpha=0.975} = 8.9 &gt; 4 \quad\rightarrow\)</span> nicht signifikant</span></p>
</section>
<section id="homogenität-der-varianz-bei-2-stichproben" class="slide level2">
<h2>Homogenität der Varianz bei &gt; 2 Stichproben</h2>
<p><br></p>
<div class="column" style="width:59%;">
<p><strong>Bartlett’s Test:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(<span class="fu">list</span>(x1, x2, x3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  list(x1, x2, x3)
Bartlett's K-squared = 7.7136, df = 2, p-value = 0.02114</code></pre>
</div>
</div>
<p><br> <strong>Fligner-Killeen Test</strong> (empfohlen):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">fligner.test</span>(<span class="fu">list</span>(x1, x2, x3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fligner-Killeen test of homogeneity of variances

data:  list(x1, x2, x3)
Fligner-Killeen:med chi-squared = 2.2486, df = 2, p-value = 0.3249</code></pre>
</div>
</div>
</div><div class="column" style="width:39%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/three-samples-1.png" width="288"></p>
</figure>
</div>
</div>
</div>
</div><ul>
<li>Tests werden häufig verwendet, um die Annahmen für eine ANOVA zu überprüfen.</li>
</ul>
</section>
<section id="empfehlung-für-zweistichproben-t-tests" class="slide level2">
<h2>Empfehlung für Zweistichproben-t-Tests</h2>
<p><br></p>
<p><strong>Traditionelles Vorgehen:</strong></p>
<ol type="1">
<li>Test auf gleiche Varianzen mit Hilfe des F-Tests: <code>var.test(x, y)</code></li>
<li>Wenn die Varianzen gleich sind: <code>t.test(x, y, var.equal = TRUE)</code></li>
<li>andernfalls: <code>t.test(x, y)</code> (= Welch-Test)</li>
<li>Prüfe, ob beide Stichproben einer Normalverteilung folgen.</li>
</ol>
<p><br></p>
<p><strong>Moderne Empfehlung (bevorzugt):</strong></p>
<ol type="1">
<li>Verwende keine Vortests!</li>
<li>Verwende immer den Welch-Test: <code>t.test(x, y)</code></li>
<li>Überprüfe die ungefähre Normalverteilung mit Box- oder QQ-Plots. Das ist weniger wichtig, wenn <span class="math inline">\(n\)</span> groß ist.</li>
</ol>
<p>siehe <span class="citation" data-cites="zimmerman_note_2004">Zimmerman (<a href="#/literatur" role="doc-biblioref" onclick="">2004</a>)</span> oder <a href="https://en.wikipedia.org/wiki/Welch%27s_t-test">Wikipedia</a>.</p>
</section>
<section id="gepaarter-t-test" class="slide level2">
<h2>Gepaarter t-Test</h2>
<ul>
<li><p>manchmal auch „t-Test für abhängige Stichproben“ genannt</p>
<ul>
<li>der Begriff „abhängig“ kann irreführend sein, „gepaart“ ist eindeutiger</li>
<li>die Werte innerhalb der Stichproben müssen immer noch unabhängig sein</li>
</ul></li>
<li><p>Beispiele: linker Arm / rechter Arm; vorher / nachher</p></li>
<li><p>ist im Wesentlichen ein Einstichproben-t-Test von paarweisen Unterschieden gegen <span class="math inline">\(\mu=0\)</span><br>
</p></li>
<li><p>Reduziert den Einfluss individueller Unterschiede („Kovariate“) dank Fokussierung auf die paarweisen Unterschiede</p></li>
</ul>
<div class="column" style="width:49%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">8</span>)</span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  x1 and x2
t = -1.372, df = 8, p-value = 0.2073
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -4.28924  1.08924
sample estimates:
mean of x mean of y 
      4.0       5.6 </code></pre>
</div>
</div>
<p>p=0.20, nicht signifikant</p>
</div><div class="column" style="width:49%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb19-2"><a aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">8</span>)</span>
<span id="cb19-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  x1 and x2
t = -4, df = 4, p-value = 0.01613
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.710578 -0.489422
sample estimates:
mean difference 
           -1.6 </code></pre>
</div>
</div>
<p>p=0.016, signifikant</p>
</div><p>Der gepaarte t-Test besitzt in diesem Fall eine größere Power (Trennschärfe).</p>
</section>
<section id="mann-whitney--und-wilcoxon-test" class="slide level2">
<h2>Mann-Whitney- und Wilcoxon-Test</h2>
<p><br></p>
<ul>
<li>Nichtparametrische Tests:
<ul>
<li>Keine Annahmen über Form und Parameter der Verteilung, aber</li>
<li>Verteilungen sollten ähnlich sein, sonst kann der Test irreführend werden.</li>
</ul></li>
<li>Basierend auf Rängen: Die Tests vergleichen die Ränge der Daten.</li>
<li>Bezeichnung “Mann-Whitney” für unabhängige Stichproben, “Wilcoxon” für gepaarte Stichproben.</li>
</ul>
<p><br> <strong>Grundprinzip:</strong> Zählung der so genannten „Inversionen“ der Ränge, d.h. wie oft sich die Reihenfolge der Stichproben überschneidet</p>
<ul>
<li>Stichprobe A: 1, 3, 4, 5, 7</li>
<li>Stichprobe B: 6, 8, 9, 10, 11</li>
<li>Beide Stichproben gemeinsam geordnet: 1, 3, 4, 5, <span class="red">6</span>, 7, <span class="red">8</span>, <span class="red">9</span>, <span class="red">10</span>, <span class="red">11</span></li>
<li>Inversionen: <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(U = 1\)</span></li>
</ul>
</section>
<section id="mann-whitney-test-in-der-praxis" class="slide level2">
<h2>Mann-Whitney-Test in der Praxis</h2>
<p><br></p>
<ol type="1">
<li>Weise den beiden Stichproben <span class="math inline">\(A\)</span> und <span class="math inline">\(B\)</span> mit dem Stichprobenumfang <span class="math inline">\(m\)</span> und <span class="math inline">\(n\)</span> die Ränge <span class="math inline">\(R_A\)</span> und <span class="math inline">\(R_B\)</span> zu.</li>
<li>Berechne die Anzahl der Inversionen <span class="math inline">\(U\)</span>:</li>
</ol>
<p><span class="math display">\[\begin{align*}
     U_A &amp;= m \cdot n + \frac{m (m + 1)}{2} - \sum_{i=1}^m R_A \\
     U_B &amp;= m \cdot n + \frac{n (n + 1)}{2} - \sum_{i=1}^n R_B \\
     U   &amp;= \min(U_A, U_B)
\end{align*}\]</span></p>
<ul>
<li>Kritische Werte von <span class="math inline">\(U\)</span> finden sich in gängigen Statistik-Lehrbüchern.</li>
<li>In <strong>R</strong> nicht notwendig, p-Wert wird direkt ausgegeben.</li>
<li><strong>Anmerkung:</strong> Verwende spezielle Version <code>wilcox.exact</code> mit Korrektur, wenn mehrfach gleiche Werte (Bindungen) vorliegen.</li>
</ul>
</section>
<section id="mann-whitney---wilcoxon-test-in-r" class="slide level2">
<h2>Mann-Whitney - Wilcoxon-Test in R</h2>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>)</span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>)</span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(A, B) <span class="co"># für gepaarte Daten optionales Argument `paired = TRUE` verwenden</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  A and B
W = 1, p-value = 0.01587
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p><br></p>
<p><strong>Mann-Whitney - Wilcoxon-Test mit Bindungskorrektur</strong></p>
<ul>
<li>wird angewendet, wenn die Rangunterschiede doppelte Werte enthalten</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>)</span>
<span id="cb23-2"><a aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"exactRankTests"</span>)</span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.exact</span>(A, B, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact Wilcoxon signed rank test

data:  A and B
V = 0, p-value = 0.0625
alternative hypothesis: true mu is not equal to 0</code></pre>
</div>
</div>
</section>
<section id="permutationsmethoden" class="slide level2">
<h2>Permutationsmethoden</h2>
<ul>
<li>Grundprinzip: Schätzung einer Teststatistik <span class="math inline">\(\xi_{obs}\)</span> aus der Stichprobe,</li>
<li>Resampling: Simulieren vieler <span class="math inline">\(\xi_{i, sim}\)</span> aus zufällig permutiertem Datensatz (<span class="math inline">\(n = 999\)</span> oder mehr)</li>
<li>Wie extrem ist <span class="math inline">\(\xi_{est}\)</span> innerhalb der geordneten Reihe der simulierten Werte <span class="math inline">\(\xi_{i, sim}\)</span>?</li>
</ul>

<img data-src="05-classtests_files/figure-revealjs/permutation-test-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Sei <span class="math inline">\(\xi_{obs}\)</span> in unserem Beispiel <span class="math inline">\(4.5\)</span>, dann sei <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(p= 0.97\)</span>.</p>
</section></section>
<section>
<section id="poweranalyse" class="title-slide slide level1 center">
<h1>Poweranalyse</h1>

</section>
<section id="bestimmung-der-power-von-statistischen-tests" class="slide level2">
<h2>Bestimmung der Power von statistischen Tests</h2>
<p><br></p>
<p><strong>Wie viele Wiederholungen benötige ich?</strong></p>
<ul>
<li><p>Hängt ab von:</p>
<ul>
<li>der relativen Effektstärke <span class="math inline">\(\frac{\mathrm{Effekt}}{\mathrm{Standardabweichung}}\)</span></li>
</ul>
<p><span class="math display">\[\delta=\frac{(\bar{x}_1-\bar{x}_2)}{s}\]</span></p>
<ul>
<li>dem Stichprobenumfang <span class="math inline">\(n\)</span></li>
<li>dem vordefinierten Signifikanzniveau <span class="math inline">\(\alpha\)</span></li>
<li>und der angewandten statistischen Methode</li>
</ul></li>
<li><p>Je kleiner <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(n\)</span> und <span class="math inline">\(\delta\)</span>, desto größer ist der Fehler zweiter Art (<span class="math inline">\(\beta\)</span>).</p></li>
<li><p>Der <span class="math inline">\(\beta\)</span>-Fehler ist die Wahrscheinlichkeit, Effekte zu übersehen, obwohl sie vorhanden sind.</p></li>
<li><p>Die Trennschärfe (Power) (<span class="math inline">\(1-\beta\)</span>) ist die Wahrscheinlichkeit, dass ein Test signifikant ist, wenn ein Effekt vorhanden ist.</p></li>
</ul>
</section>
<section id="poweranalyse-1" class="slide level2">
<h2>Poweranalyse</h2>
<p><br></p>
<p>Formel für den Mindeststichprobenumfang im Einstichprobenfall:</p>
<p><span class="math display">\[
n = \bigg(\frac{z_\alpha + z_{1-\beta}}{\delta}\bigg)^2
\]</span></p>
<ul>
<li><span class="math inline">\(z\)</span>: die Quantile (<code>qnorm</code>) der Standardnormalverteilung für <span class="math inline">\(\alpha\)</span> und für <span class="math inline">\(1-\beta\)</span></li>
<li><span class="math inline">\(\delta=\Delta / s\)</span>: relative Effektstärke.</li>
</ul>
<p><strong>Beispiel</strong></p>
<p>Zweiseitiger Test mit <span class="math inline">\(\alpha=0.025\)</span> und <span class="math inline">\(\beta=0.2\)</span></p>
<p><span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(z_\alpha = 1.96\)</span>, <span class="math inline">\(z_\beta=0.84\)</span>, dann:</p>
<p><span class="math display">\[
n= (1.96 + 0.84)^2 \cdot 1/\delta^2 \approx 8 /\delta^2
\]</span></p>
<p><span class="math inline">\(\delta = 1.0\cdot \sigma\)</span> <span class="math inline">\(\qquad\Rightarrow\)</span> <span class="red">n &gt; 8</span></p>
<p><span class="math inline">\(\delta = 0.5\cdot \sigma\)</span> <span class="math inline">\(\qquad\Rightarrow\)</span> <span class="red">n &gt; 32</span></p>
</section>
<section id="power-des-t-tests" class="slide level2">
<h2>Power des t-Tests</h2>
<p>Die Trennschärfe eines t-Tests bzw. der Mindeststichprobenumfang kann mit der Funktion <code>power.t.test()</code> geschätzt werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n=</span><span class="dv">5</span>, <span class="at">delta=</span><span class="fl">0.5</span>, <span class="at">sig.level=</span><span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 5
          delta = 0.5
             sd = 1
      sig.level = 0.05
          power = 0.1038399
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p><span class="math inline">\(\rightarrow\)</span> ‘power’ = 0.10</p>
<ul>
<li>Für <span class="math inline">\(n=5\)</span> wird ein vorhandener Effekt von <span class="math inline">\(0.5 \sigma\)</span> nur in 1 von 10 Fällen entdeckt.</li>
<li>Für eine Power von 80% bei <span class="math inline">\(n=5\)</span> wird Effektstärke von mindestens <span class="math inline">\(2\sigma\)</span> benötigt:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">n=</span><span class="dv">5</span>, <span class="at">power=</span><span class="fl">0.8</span>, <span class="at">sig.level=</span><span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Für einen schwachen Effekt von <span class="math inline">\(0.5\sigma\)</span> wird <span class="math inline">\(n\ge 64\)</span> in jeder Gruppe benötig:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">power.t.test</span>(<span class="at">delta=</span><span class="fl">0.5</span>,<span class="at">power=</span><span class="fl">0.8</span>,<span class="at">sig.level=</span><span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="darkred"><span class="math inline">\(\Rightarrow\)</span> Man braucht entweder einen großen Stichprobenumfang oder einen starken Effekt.</span></p>
</section>
<section id="simulierte-power-eines-t-tests" class="slide level2">
<h2>Simulierte Power eines t-Tests</h2>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Grundgesamtheitsparameter</span></span>
<span id="cb30-2"><a aria-hidden="true" tabindex="-1"></a>n      <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb30-3"><a aria-hidden="true" tabindex="-1"></a>xmean1 <span class="ot">&lt;-</span> <span class="dv">50</span>; xmean2 <span class="ot">&lt;-</span> <span class="dv">55</span></span>
<span id="cb30-4"><a aria-hidden="true" tabindex="-1"></a>xsd1   <span class="ot">&lt;-</span> xsd2 <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb30-5"><a aria-hidden="true" tabindex="-1"></a>alpha  <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb30-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a aria-hidden="true" tabindex="-1"></a>nn <span class="ot">&lt;-</span> <span class="dv">1000</span>   <span class="co"># Anzahl an Testläufen der Simulation</span></span>
<span id="cb30-8"><a aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> b <span class="ot">&lt;-</span> <span class="dv">0</span>  <span class="co"># initialisiere Zähler</span></span>
<span id="cb30-9"><a aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nn) {</span>
<span id="cb30-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="co"># erstelle Zufallszahlen</span></span>
<span id="cb30-11"><a aria-hidden="true" tabindex="-1"></a>  x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, xmean1, xsd1)</span>
<span id="cb30-12"><a aria-hidden="true" tabindex="-1"></a>  x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, xmean2, xsd2)</span>
<span id="cb30-13"><a aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ergebnisse des t-Tests</span></span>
<span id="cb30-14"><a aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">t.test</span>(x1,x2,<span class="at">var.equal =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>p.value </span>
<span id="cb30-15"><a aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (p <span class="sc">&lt;</span> alpha) {</span>
<span id="cb30-16"><a aria-hidden="true" tabindex="-1"></a>     a <span class="ot">&lt;-</span> a<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb30-17"><a aria-hidden="true" tabindex="-1"></a>   } <span class="cf">else</span> {</span>
<span id="cb30-18"><a aria-hidden="true" tabindex="-1"></a>     b <span class="ot">&lt;-</span> b<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb30-19"><a aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb30-20"><a aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-21"><a aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"a="</span>, a, <span class="st">", b="</span>, b, <span class="st">", a/n="</span>, a<span class="sc">/</span>nn, <span class="st">", b/n="</span>, b<span class="sc">/</span>nn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>allgemeingültiges Verfahren, auch für andere Tests geeignet.</li>
</ul>
</section></section>
<section>
<section id="test-auf-verteilungen" class="title-slide slide level1 center">
<h1>Test auf Verteilungen</h1>

</section>
<section id="testen-auf-verteilungen" class="slide level2">
<h2>Testen auf Verteilungen</h2>
<p><br></p>
<p><strong>Nominale Variablen</strong></p>
<ul>
<li><span class="math inline">\(\chi^2\)</span>-Test</li>
<li>Exakter Test von Fisher</li>
</ul>
<p><strong>Ordinale Variablen</strong></p>
<ul>
<li>Cramér-von-Mises-Test</li>
<li><span class="math inline">\(\rightarrow\)</span> stärker als <span class="math inline">\(\chi^2\)</span> oder KS-Test</li>
</ul>
<p><strong>Metrische Skalen</strong></p>
<ul>
<li>Kolmogorov-Smirnov-Test (KS-Test)</li>
<li>Shapiro-Wilk-Test (für Normalverteilung)</li>
<li>Grafische Prüfungen</li>
</ul>
</section>
<section id="mehrfeldertafeln-für-nominale-variablen" class="slide level2">
<h2>Mehrfeldertafeln für nominale Variablen</h2>
<ul>
<li>Werden für nominale (d.&nbsp;h. kategoriale oder qualitative) Daten verwendet.</li>
<li>Beispiele: Augen- und Haarfarbe, medizinische Behandlung und Anzahl der geheilten/nicht geheilten Personen</li>
<li>Wichtig: Verwende <strong>absolute Messwerte</strong> (echte Zahlen!), keine Prozentsätze oder andere berechnete Daten (also nicht etwa Biomasse pro Fläche)</li>
</ul>
<p><strong>Beispiel:</strong> Verteilung von Daphnien (Wasserflöhen) in den Wasserschichten eines Sees:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Klon</th>
<th style="text-align: center;">Obere Schicht</th>
<th style="text-align: center;">Tiefe Schicht</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">A</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">87</td>
</tr>
<tr class="even">
<td style="text-align: right;">B</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">78</td>
</tr>
<tr class="odd">
<td style="text-align: right;">C</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">45</td>
</tr>
</tbody>
</table>
<ul>
<li>In der oberen Schicht wurden die Futteralgen bereits aufgefressen. Sie finden sich nur noch im sauerstoffarmen Tiefenwasser.</li>
<li>genetisch angepasste Klone mit höherem Hämoglobingehalt können in sauerstoffreies Wasser tauchen</li>
</ul>
</section>
<section id="rechenschema-des-chi2-tests" class="slide level2">
<h2>Rechenschema des <span class="math inline">\(\chi^2\)</span>-Tests</h2>
<ol type="1">
<li>Beobachtete Häufigkeiten <span class="math inline">\(O_{ij}\)</span></li>
</ol>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Klon A</th>
<th>Klon B</th>
<th>Klon C</th>
<th>Summe <span class="math inline">\(s_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Obere Schicht</td>
<td>50</td>
<td>37</td>
<td>72</td>
<td>159</td>
</tr>
<tr class="even">
<td>Untere Schicht</td>
<td>87</td>
<td>78</td>
<td>45</td>
<td>210</td>
</tr>
<tr class="odd">
<td>Summe <span class="math inline">\(s_j\)</span></td>
<td>137</td>
<td>115</td>
<td>117</td>
<td><span class="math inline">\(n=369\)</span></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<ol start="2" type="1">
<li>Erwartete Häufigkeiten <span class="math inline">\(E_{ij} = s_i \cdot s_j / n\)</span> <span class="gray">(Gleichverteilung = Nullhypothese)</span></li>
</ol>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Klon A</th>
<th>Klon B</th>
<th>Klon C</th>
<th>Summe <span class="math inline">\(s_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Obere Schicht</td>
<td>59.0</td>
<td>49.6</td>
<td>50.4</td>
<td>159</td>
</tr>
<tr class="even">
<td>Untere Schicht</td>
<td>78.0</td>
<td>65.4</td>
<td>66.6</td>
<td>210</td>
</tr>
<tr class="odd">
<td>Summe <span class="math inline">\(s_j\)</span></td>
<td>137</td>
<td>115</td>
<td>117</td>
<td><span class="math inline">\(n=369\)</span></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<ol start="3" type="1">
<li><p>Teststatistik <span class="math inline">\(\hat{\chi}^2 = \sum_{i, j} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}\)</span></p></li>
<li><p>Vergleich mit kritischem <span class="math inline">\(\chi^2\)</span> aus der Tabelle <span class="gray">mit <span class="math inline">\((n_{Zeile} - 1) \cdot (n_{Spalte} - 1)\)</span> df.</span></p></li>
</ol>
</section>
<section id="der-chi2-test-in-r" class="slide level2">
<h2>Der <span class="math inline">\(\chi^2\)</span>-Test in <strong>R</strong></h2>
<p><br></p>
<p>Organisiere die Daten in einer Matrix mit 3 Zeilen (für die Klone) und 2 Spalten (für die Tiefen):</p>
<div class="bigfont">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">37</span>, <span class="dv">72</span>, <span class="dv">87</span>, <span class="dv">78</span>, <span class="dv">45</span>), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb31-2"><a aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]   50   87
[2,]   37   78
[3,]   72   45</code></pre>
</div>
</div>
</div>
<div class="bigfont">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  x
X-squared = 24.255, df = 2, p-value = 5.408e-06</code></pre>
</div>
</div>
</div>
<ul>
<li>Anmerkung: Die Ergebnisse sind nur zuverlässig, wenn alle beobachteten Häufigkeiten <span class="math inline">\(\geq 5\)</span> sind.</li>
<li>Für kleinere Stichproben ist der exakte Test von Fisher zu verwenden.</li>
</ul>
</section>
<section id="exakter-test-nach-fisher" class="slide level2">
<h2>Exakter Test nach Fisher</h2>
<p><br></p>
<div class="bigfont">
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">37</span>, <span class="dv">72</span>, <span class="dv">87</span>, <span class="dv">78</span>, <span class="dv">45</span>), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb35-2"><a aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]   50   87
[2,]   37   78
[3,]   72   45</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  x
p-value = 5.807e-06
alternative hypothesis: two.sided</code></pre>
</div>
</div>
</div>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> signifikante Korrelation zwischen den Klonen und der vertikalen Verteilung im See.</p>
</section>
<section id="lieblingszahlen-von-hse-studenten" class="slide level2">
<h2>Lieblingszahlen von HSE-Studenten</h2>

<img data-src="05-classtests_files/figure-revealjs/favorite-numbers-1.png" width="960" class="r-stretch"><ul>
<li>Zahlen von 1..9, <span class="math inline">\(n=34\)</span></li>
<li><span class="math inline">\(H_0\)</span>: gleiche Wahrscheinlichkeit für alle Zahlen <span class="math inline">\(1/9\)</span> (diskrete Gleichverteilung)</li>
<li><span class="math inline">\(H_A\)</span>: einige Zahlen bevorzugt <span class="math inline">\(\rightarrow\)</span> weichen von diskreter Gleichverteilung ab</li>
</ul>
</section>
<section id="chi-quadrat-test" class="slide level2">
<h2>Chi-Quadrat-Test</h2>
<p><br></p>
<div class="bigfont">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-hidden="true" tabindex="-1"></a>obsfreq <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">6</span>, <span class="dv">3</span>)</span>
<span id="cb39-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(obsfreq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  obsfreq
X-squared = 13.647, df = 8, p-value = 0.09144</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(obsfreq, <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>, <span class="at">B =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities with simulated p-value (based
    on 1000 replicates)

data:  obsfreq
X-squared = 13.647, df = NA, p-value = 0.0969</code></pre>
</div>
</div>
</div>
<p><br></p>
<ul>
<li><strong>Einstichproben</strong> <span class="math inline">\(\chi^2\)</span>-Test. Er testet auf Gleichheit der Häufigkeit in allen Klassen.</li>
<li>Die simulationsbasierte Version des Tests (mit 1000 Wiederholungen) ist etwas genauer als der Standard-<span class="math inline">\(\chi^2\)</span>-Test, aber beide sind nicht signifikant.</li>
</ul>
</section>
<section id="cramér-von-mises-test" class="slide level2">
<h2><span class="gray">Cramér-von-Mises-Test</span></h2>

<img data-src="05-classtests_files/figure-revealjs/von-mises-1.png" width="960" class="r-stretch"><p><span class="math display">\[
T = n \omega^2 = \frac{1}{12n} + \sum_{i=1}^n \left[ \frac{2i-1}{2n}-F(x_i) \right]^2
\]</span></p>
</section>
<section id="cramér-von-mises-test-in-r" class="slide level2">
<h2><span class="gray">Cramér-von-Mises-Test in <strong>R</strong></span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dgof)</span>
<span id="cb43-2"><a aria-hidden="true" tabindex="-1"></a>obsfreq <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">6</span>, <span class="dv">3</span>)</span>
<span id="cb43-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a aria-hidden="true" tabindex="-1"></a><span class="do">## CvM-Test benötigt Einzelwerte, nicht Klassenhäufigkeiten</span></span>
<span id="cb43-5"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(obsfreq), obsfreq)</span>
<span id="cb43-6"><a aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1 2 3 3 3 3 3 3 4 4 5 5 6 6 6 6 6 7 7 7 7 7 7 7 7 8 8 8 8 8 8 9 9 9</code></pre>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a aria-hidden="true" tabindex="-1"></a><span class="do">## erstelle kumulative Verteilung mit identischer Wahrscheinlichkeit für alle Fälle</span></span>
<span id="cb45-2"><a aria-hidden="true" tabindex="-1"></a>cdf <span class="ot">&lt;-</span> <span class="fu">stepfun</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="fu">cumsum</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">9</span>, <span class="dv">9</span>))))</span>
<span id="cb45-3"><a aria-hidden="true" tabindex="-1"></a>cdf <span class="ot">&lt;-</span> <span class="fu">ecdf</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>)</span>
<span id="cb45-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a aria-hidden="true" tabindex="-1"></a><span class="do">## führe den Test durch</span></span>
<span id="cb45-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cvm.test</span>(x, cdf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Cramer-von Mises - W2

data:  x
W2 = 0.51658, p-value = 0.03665
alternative hypothesis: Two.sided</code></pre>
</div>
</div>
<ul>
<li>Der Cramér-von-Mises-Test arbeitet mit den ursprünglichen, nicht in klassen eingeteilten Werten.</li>
<li>Verwendung der kumulativen Verteilungsfunktion <span class="blue">berücksichtigt die Reihenfolge der Klassen</span> <span class="math inline">\(\rightarrow\)</span> leistungsfähiger als <span class="math inline">\(\chi^2\)</span>-Test.</li>
</ul>
</section></section>
<section>
<section id="testen-auf-normalverteilung" class="title-slide slide level1 center">
<h1>Testen auf Normalverteilung</h1>

</section>
<section id="testen-oder-prüfen" class="slide level2">
<h2>Testen oder Prüfen?</h2>
<p><strong>Philosophisches Problem:</strong> Wir wollen <span class="math inline">\(H_0\)</span> <span class="red">behalten</span>!</p>
<ul>
<li>Gleichheit kann nicht getestet werden <span class="math inline">\(\rightarrow\)</span> deshalb graphisch prüfen</li>
</ul>
<p><strong>Plausibilitätsprüfung:</strong> Vor der Analyse nachdenken!</p>
<ul>
<li>Was ist der Prozess der Datenerzeugung <span class="math inline">\(\rightarrow\)</span> fachlicher Kontext?</li>
<li>Macht die Normalverteilung für die Daten „Sinn“?</li>
<li>Sind die Daten metrisch (kontinuierlich)?</li>
<li>Ist der Variationskoeffizient <span class="math inline">\(cv=s/\bar{x}\)</span> &lt; 0.33 (oder zumindest &lt; 0.5)?<br> <span class="smallfont">Wenn die Daten zu nahe an der Null liegen: rechtsschiefe Verteilung wahrscheinlich.</span></li>
</ul>
<p><strong>Intrinsische Nicht-Normalität</strong></p>
<blockquote>
<p>Einige Datentypen, wie z. B. Zähldaten (z. B. Anzahl der Vorkommnisse) oder binäre Daten (z. B. Ja/Nein), sind von Natur aus nicht normalverteilt.</p>
</blockquote>
<ul>
<li>Binäre Daten: Arbeite mit Originaldaten und Binomialverteilung statt Prozentzahlen.</li>
<li>Zähldaten: Nutze Methoden für die Poisson-Verteilung.</li>
</ul>
</section>
<section id="shapiro-wilk-w-test" class="slide level2">
<h2>Shapiro-Wilk-W-Test <span class="red">?</span></h2>
<p><span class="math inline">\(\rightarrow\)</span> Ziel: prüft, ob eine Stichprobe aus einer Normalverteilung stammt</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb47-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  x
W = 0.99064, p-value = 0.7165</code></pre>
</div>
</div>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> der <span class="math inline">\(p\)</span>-Wert ist größer als 0.05, also würden wir <span class="math inline">\(H_0\)</span> behalten und schlussfolgern, dass nichts gegen die Annahme der Normalität spricht</p>
<p><br></p>
<p>Die Interpretation des Shapiro-Wilk-Tests ist mit Vorsicht zu betrachten:</p>
<ul>
<li>für kleine <span class="math inline">\(n\)</span> nicht empfindlich genug</li>
<li>bei großem <span class="math inline">\(n\)</span> überempfindlich</li>
<li>Formale Tests, wie Shapiro-Wilk, <span class="math inline">\(\chi^2\)</span>- (Chi-Quadrat-) oder Kolmogorov-Smirnov, werden zur Überprüfung der Normalitätsannahme für t-Tests und ANOVA <span class="red">nicht mehr empfohlen</span>.</li>
<li>für andere Testprobleme durchaus nützlich.</li>
</ul>
</section>
<section id="alternative-verwendung-grafischer-methoden" class="slide level2">
<h2>Alternative: Verwendung grafischer Methoden</h2>

<img data-src="05-classtests_files/figure-revealjs/normality-graphical-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p><br></p>
<ul>
<li>Histogramm, Boxplot, QQ-Plot (=Quantil-Quantil-Plot)</li>
<li>siehe auch: Box-Cox-Methode</li>
</ul>
</section>
<section id="grafische-überprüfung-der-normalität" class="slide level2">
<h2>Grafische Überprüfung der Normalität</h2>
<p><br></p>
<div class="column" style="width:49%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/distrbox-examples-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:49%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/qqnorm-examples-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div><ul>
<li><span class="math inline">\(x\)</span>: theoretische Quantile, wo die Werte bei Vorliegen einer Normalverteilung gefunden werden sollten</li>
<li><span class="math inline">\(y\)</span>: normalisierte und geordnete Messwerte (<span class="math inline">\(z\)</span>-Werte)</li>
<li>skaliert in der Einheit der Standardabweichungen</li>
<li>Normalverteilung liegt vor, wenn die Punkte einer Geraden folgen</li>
</ul>
</section>
<section id="prüfung-der-verteilung-für-deskriptive-zwecke" class="slide level2">
<h2>Prüfung der Verteilung für deskriptive Zwecke</h2>
<p><br></p>
<p>In manchen Disziplinen, z.B. in der Hydrologie, möchte man gelegentlich wissen, welcher Verteilungstyp einen Datensatz am besten beschreibt. Ein Beispiel ist die Extremwertanalyse (z.B. 100-jähriges Hochwasser), da hier das Central Limit Theorem (CLT) nicht greift.</p>
<p><strong>Vorgehensweise</strong></p>
<ol type="1">
<li>Visuelle Prüfung (besonders auf die tails achten)
<ul>
<li>Histogramm (erster Eindruck)</li>
<li>Q-Q-Plots (genauere Passform)</li>
</ul></li>
<li>Formale Tests zur Ergänzung (Ausschlussprinzip)
<ul>
<li>Tests: Kolmogorov-Smirnov, Cramér-von Mises oder Anderson-Darling</li>
<li>Ablehnung des Verteilungstyps bei signifikantem <span class="math inline">\(p &lt; 0.05\)</span>.</li>
</ul></li>
<li>Modellselektion
<ul>
<li>Nutzung von AIC/BIC zur Identifikation des optimalen Modells</li>
<li>Berücksichtigung der physikalischen Plausibilität der Parameter</li>
</ul></li>
</ol>
</section></section>
<section>
<section id="transformationen" class="title-slide slide level1 center">
<h1>Transformationen</h1>

</section>
<section id="transformationen-1" class="slide level2">
<h2>Transformationen</h2>
<ul>
<li>Ermöglicht die Anwendung von Methoden, die für normalverteilte Daten entwickelt wurden, auf nicht-normalverteilte Fälle.</li>
<li>Einige moderne Methoden (z. B. verallgemeinerte lineare Modelle, GLM) können bestimmte Verteilungen direkt verarbeiten, z.B. Binomial-, Gamma- oder Poisson-Verteilung.</li>
</ul>
<p><strong>Transformationen für rechtsschiefe Daten</strong></p>
<ul>
<li><span class="math inline">\(x'=\log(x)\)</span></li>
<li><span class="red"><span class="math inline">\(x'=\log(x + a)\)</span></span></li>
<li><span class="math inline">\(x'=(x+a)^c\)</span> <span class="gray">(<span class="math inline">\(a\)</span> zwischen 0,5 und 1)</span></li>
<li><span class="math inline">\(x'=1/x\)</span> <span class="gray">(„sehr stark“, d.h. in den meisten Fällen zu extrem)</span></li>
<li><span class="math inline">\(x'=a - 1/\sqrt{x}\)</span> <span class="gray">(um die Skalierung zu vereinfachen)</span></li>
<li><span class="math inline">\(x'=1/\sqrt{x}\)</span> <span class="gray">(Kompromiss zwischen <span class="math inline">\(\ln\)</span> und <span class="math inline">\(1/x\)</span>)</span></li>
<li><span class="math inline">\(x'=a+bx^c\)</span> <span class="gray">(sehr allgemein, schließt Potenzen und Wurzeln ein)</span></li>
</ul>
</section>
<section id="transformationen-ii" class="slide level2">
<h2>Transformationen II</h2>
<p><strong>Transformationen für Zähldaten</strong></p>
<ul>
<li><span class="math inline">\(x'=\sqrt{3/8+x}\)</span> <span class="gray">(Zählungen: 1, 2, 3 <span class="math inline">\(\rightarrow\)</span> 0.61, 1.17, 1.54, 1.84, )</span></li>
<li><span class="math inline">\(x'=\lg(x+3/8)\)</span></li>
<li><span class="math inline">\(x'=\log(\log(x))\)</span> <span class="gray">für riesige Zahlen</span></li>
</ul>
<p><span class="blue"><span class="math inline">\(\rightarrow\)</span> besser: ein GLM der Familien Poisson oder Quasi-Poisson in Betracht ziehen</span></p>
<p><strong>Verhältnisse und Prozentsätze</strong></p>
<ul>
<li><span class="math inline">\(x'=\arcsin \sqrt{x/n}\)</span></li>
<li><span class="math inline">\(x'=\arcsin \sqrt{\frac{x+3/8}{n+3/4}}\)</span></li>
</ul>
<p><span class="blue"><span class="math inline">\(\rightarrow\)</span> besser: ein GLM mit Binomialverteilung in Betracht ziehen</span> <!-----------------------------------------------------------------------------/ --></p>
</section>
<section id="wie-findet-man-die-beste-transformation" class="slide level2">
<h2>Wie findet man die beste Transformation?</h2>
<ul>
<li>Beispiel: Biovolumen von Kieselalgenzellen <span class="gray">(Art <em>Nitzschia acicularis</em>)</span>.</li>
</ul>
<div class="column" style="width:42%;">
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"prk_nit.csv"</span>)</span>
<span id="cb49-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a aria-hidden="true" tabindex="-1"></a>Nit85 <span class="ot">&lt;-</span> dat<span class="sc">$</span>biovol[dat<span class="sc">$</span>group <span class="sc">==</span> <span class="st">"nit85"</span>]</span>
<span id="cb49-4"><a aria-hidden="true" tabindex="-1"></a>Nit90 <span class="ot">&lt;-</span> dat<span class="sc">$</span>biovol[dat<span class="sc">$</span>group <span class="sc">==</span> <span class="st">"nit90"</span>]</span>
<span id="cb49-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Nit85, <span class="at">xlab=</span><span class="st">"Biovolume (mm^3)"</span>)</span>
<span id="cb49-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Nit90, <span class="at">xlab=</span><span class="st">"Biovolume (mm^3)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:52%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/prk_nit_fig-1.png" width="576"></p>
</figure>
</div>
</div>
</div>
</div><ul>
<li>Rechtsschiefe Verteilung.</li>
<li>Berechnungen des Biovolumens für Studien zum Nahrungsnetz und zur Vorhersage von Algenmassenentwicklungen.</li>
</ul>

<aside><div>
<p>Mehr über <strong>Nitzschia</strong> in <a href="https://en.wikipedia.org/wiki/Nitzschia">Wikipedia</a></p>
<p>Datensatz <a href="&quot;https://github.com/tpetzoldt/datasets/blob/main/data/prk_nit.csv&quot;"><code>prk_nit.csv</code></a> und Metadaten <a href="&quot;https://github.com/tpetzoldt/datasets/blob/main/data/prk_nit_info.txt&quot;"><code>prk_nit_info.txt</code></a> verfügbar unter <a href="https://github.com/tpetzoldt/datasets">https://github.com/tpetzoldt/datasets</a>.</p>
</div></aside></section>
<section id="box-cox-methode" class="slide level2">
<h2>Box-Cox Methode</h2>
<p>Abschätzung der optimalen Transformation aus der Klasse der Potenzen und Logarithmen:</p>
<p><span class="math display">\[
y' = \begin{cases} \frac{y^\lambda - 1}{\lambda} &amp; \text{wenn } \lambda \neq 0 \\ \ln(y) &amp; \text{wenn } \lambda = 0 \end{cases}
\]</span></p>
<p>In vielen praktischen Fällen kann man statt <span class="math inline">\(\frac{y^\lambda - 1}{\lambda}\)</span> vereinfacht <span class="math inline">\(y^\lambda\)</span> verwenden.</p>
<p><br></p>
<div class="column" style="width:42%;">
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb50-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(Nit90 <span class="sc">~</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:52%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/boxcox-1.png" width="384"></p>
</figure>
</div>
</div>
</div>
</div><ul>
<li>Argument von <code>boxcox</code> ist eine sogenannte „Modellformel“ oder das Ergebnis eines linearen Modells (<code>lm</code>)</li>
<li>Die einfachste Form ist das „Nullmodell“ ohne Erklärungsvariablen (<code>~ 1</code>).</li>
<li>Mehr über Modellformeln, siehe ANOVA Kapitel.</li>
</ul>
</section>
<section id="box-cox-methode-ergebnisse" class="slide level2">
<h2>Box-Cox Methode: Ergebnisse</h2>
<div class="column" style="width:47%;">
<p><br></p>
<h3 id="interpretation">Interpretation</h3>
<p><br></p>
<ul>
<li>Die gepunkteten vertikalen Linien und die horizontale 95%-Linie zeigen die Vertrauensgrenzen für mögliche Transformationen.</li>
<li>Die Zahlen sind angenähert <span class="math inline">\(\rightarrow\)</span> eine Dezimalstelle genügt.</li>
<li>Hier können wir entweder eine <strong>log</strong>-Transformation (<span class="math inline">\(\lambda=0\)</span>) oder eine Potenz von <span class="math inline">\(\approx 0.5\)</span> verwenden.</li>
</ul>
</div><div class="column" style="width:5%;">

</div><div class="column" style="width:47%;">
<p>Direkte Ermittlung des Zahlenwerts:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a aria-hidden="true" tabindex="-1"></a>bc <span class="ot">&lt;-</span> <span class="fu">boxcox</span>(Nit90 <span class="sc">~</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/boxcox_interpretation-1.png" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(bc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ x: num [1:100] -2 -1.96 -1.92 -1.88 -1.84 ...
 $ y: num [1:100] -237 -233 -230 -226 -223 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a aria-hidden="true" tabindex="-1"></a>bc<span class="sc">$</span>x[bc<span class="sc">$</span>y <span class="sc">==</span> <span class="fu">max</span>(bc<span class="sc">$</span>y)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1818182</code></pre>
</div>
</div>
</div></section>
<section id="test-von-gepoolten-stichproben-mit-unterschiedlichen-mittelwerten" class="slide level2">
<h2>Test von gepoolten Stichproben mit unterschiedlichen Mittelwerten</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">boxcox</span>(biovol <span class="sc">~</span> group, <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="05-classtests_files/figure-revealjs/boxcox2-1.png" class="quarto-figure quarto-figure-center r-stretch" width="576"><ul>
<li>Um die gemeinsame Verteilung aller Gruppen auf einmal zu testen, gibt man die Erklärungsvariablen auf der rechten Seite der Modellformel an: <code>biovol ~ group</code></li>
<li>Die optimale Transformation für beide Stichproben zusammen ist <strong>log</strong>.</li>
</ul>
</section></section>
<section>
<section id="korrelation-und-regression" class="title-slide slide level1 center">
<h1>Korrelation und Regression</h1>

</section>
<section id="korrelation" class="slide level2">
<h2>Korrelation</h2>
<p><br></p>
<p><strong>Häufigkeiten von nominalen Variablen</strong></p>
<ul>
<li><span class="math inline">\(\chi^2\)</span>-Test</li>
<li>Exakter Test von Fisher</li>
</ul>
<p>⇒ Abhängigkeit zwischen Pflanzenart und Bodentyp</p>
<p><span class="gray">(siehe oben)</span></p>
<p><strong>Ordinale Variablen</strong></p>
<ul>
<li>Spearman-Korrelation</li>
</ul>
<p><span class="math inline">\(\rightarrow\)</span> Rangzahlen</p>
<p><strong>Metrische Skalen</strong></p>
<ul>
<li>Pearson-Korrelation</li>
<li>Spearman-Korrelation</li>
</ul>
</section>
<section id="varianz-und-kovarianz" class="slide level2">
<h2>Varianz und Kovarianz</h2>
<p><br></p>
<div class="column" style="width:59%;">
<p><strong>Varianz</strong></p>
<ul>
<li>misst die Variation einer einzelnen Variablen</li>
</ul>
<p><span class="math display">\[
  s^2_x = \frac{\text{Quadratsumme}}{\text{Freiheitsgrade}}=\frac{\sum_{i=1}^n (x_i-\bar{x})^2}{n-1}
\]</span></p>
<p><strong>Kovarianz</strong></p>
<ul>
<li>misst, wie sich zwei Variablen gemeinsam verändern</li>
</ul>
<p><span class="math display">\[
  q_{x,y} = \frac{\sum_{i=1}^n (x_i-\bar{x})(y_i-\bar{y})}{n-1}
\]</span></p>
<p>Korrelation: skaliert auf <span class="math inline">\((-1, +1)\)</span></p>
<p><span class="math display">\[
  r_{x,y} = \frac{q_{x,y}}{s_x \cdot s_y}
\]</span></p>
</div><div class="column" style="width:39%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/var-covar-1.png" width="288"></p>
</figure>
</div>
</div>
</div>
</div></section>
<section id="korrelationskoeffizient-nach-pearson" class="slide level2">
<h2>Korrelationskoeffizient nach Pearson</h2>
<p><br></p>
<div class="column" style="width:69%;">
<ul>
<li>der übliche Korrelationskoeffizient, den wir alle kennen</li>
<li>testet auf <span class="blue">lineare Abhängigkeit</span></li>
</ul>
<p><span class="math display">\[
r_p=\frac{\sum{(x_i-\bar{x})  (y_i-\bar{y})}}
       {\sqrt{\sum(x_i-\bar{x})^2\sum(y_i-\bar{y})^2}}
\]</span></p>
<p><strong>Oder:</strong></p>
<p><span class="math display">\[
r_p=\frac {\sum xy - \sum y \sum y / n}
        {\sqrt{(\sum x^2-(\sum x)^2/n)(\sum y^2-(\sum y)^2/n)}}
\]</span> <br></p>
<p>Wertebereich: <span class="math inline">\(-1 \le r_p \le +1\)</span></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\)</span></td>
<td>keine gegenseitige Abhängigkeit</td>
</tr>
<tr class="even">
<td><span class="math inline">\(+1 \,\text{or}\,-1\)</span></td>
<td>strikt positive bzw. negative Abhängigkeit</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0 &lt; |r_p| &lt; 1\)</span></td>
<td>positive bzw. negative Abhängigkeit</td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:29%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/pearson1-1.png" width="384"></p>
</figure>
</div>
</div>
</div>
</div></section>
<section id="welcher-korrelationskoeffizient-deutet-auf-eine-abhängigkeit-hin" class="slide level2">
<h2>Welcher Korrelationskoeffizient deutet auf eine Abhängigkeit hin?</h2>
<div class="column" style="width:49%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/pearson2-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(r=0.4, \quad p=0.0039\)</span></p>
</div><div class="column" style="width:49%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="05-classtests_files/figure-revealjs/pearson3-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(r=0.85, \quad p=0.07\)</span></p>
</div></section>
<section id="signifikante-korrelation" class="slide level2">
<h2>Signifikante Korrelation?</h2>
<p><span class="math display">\[
\hat{t}_{\alpha/2;n-2} =\frac{|r_p|\sqrt{n-2}}{\sqrt{1-r^2_p}}
\]</span></p>
<p><span class="math inline">\(t=0.829 \cdot \sqrt{1000-2}/\sqrt{1-0.829^2}=46.86, df=998\)</span></p>
<p><br> <strong>Schnelltest: kritische Werte für <span class="math inline">\(r_p\)</span></strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(n\)</span></td>
<td style="text-align: right;">d.f.</td>
<td style="text-align: right;"><span class="math inline">\(t\)</span></td>
<td style="text-align: right;"><span class="math inline">\(r_{krit}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12.706</td>
<td style="text-align: right;">0.997</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3.182</td>
<td style="text-align: right;">0.878</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2.306</td>
<td style="text-align: right;">0.633</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">2.101</td>
<td style="text-align: right;">0.445</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">2.011</td>
<td style="text-align: right;">0.280</td>
</tr>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">1.984</td>
<td style="text-align: right;">0.197</td>
</tr>
<tr class="even">
<td style="text-align: right;">1000</td>
<td style="text-align: right;">998</td>
<td style="text-align: right;">1.962</td>
<td style="text-align: right;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</section>
<section id="rangkorrelation-nach-spearman" class="slide level2">
<h2>Rangkorrelation nach Spearman</h2>
<p><br></p>
<ul>
<li>misst <strong>monotone</strong> (und nicht unbedingt lineare) Abhängigkeiten</li>
<li>Schätzung aus Rangunterschieden:</li>
</ul>
<p><span class="math display">\[
r_s=1-\frac{6 \sum d^2_i}{n(n^2-1)}
\]</span></p>
<ul>
<li>alternativ: Pearson-Korrelation der rang-transformierten Daten (notwendig bei Bindungen).</li>
<li>Test: für <span class="math inline">\(n &lt; 10\)</span> <span class="math inline">\(\rightarrow\)</span> Tabelle der kritischen Werte</li>
</ul>
<p>für <span class="math inline">\(10 \leq n\)</span> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(t\)</span>-Verteilung</p>
<p><span class="math display">\[
   \hat{t}_{1-\frac{\alpha}{2};n-2}
      =\frac{|r_s|}{\sqrt{1-r^2_S}} \sqrt{n-2}
\]</span></p>

<aside><div>
<p>Computerstatistikpakete verwenden einen speziellen Algorithmus (Algorithmus AS 89 nach Best und Roberts, 1975).</p>
</div></aside></section>
<section id="beispiel" class="slide level2">
<h2>Beispiel</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\(x\)</span></th>
<th style="text-align: right;"><span class="math inline">\(y\)</span></th>
<th><span class="math inline">\(R_x\)</span></th>
<th><span class="math inline">\(R_y\)</span></th>
<th><span class="math inline">\(d\)</span></th>
<th><span class="math inline">\(d^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">2.7</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">7.4</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">20.1</td>
<td>3</td>
<td>3</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">500.0</td>
<td>4</td>
<td>5</td>
<td>-1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>5</td>
<td style="text-align: right;">148.4</td>
<td>5</td>
<td>4</td>
<td>+1</td>
<td>1</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: right;"></td>
<td></td>
<td></td>
<td></td>
<td>2</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
r_s=1-\frac{6 \cdot 2}{5\cdot (25-1)}=1-\frac{12}{120}=0.9
\]</span></p>
<p>Zum Vergleich: <span class="math inline">\(r_p=0.58\)</span></p>
</section>
<section id="anwendung-von-spearmans-r_s" class="slide level2">
<h2>Anwendung von Spearman’s-<span class="math inline">\(r_s\)</span></h2>
<p><br></p>
<p><strong>Vorteile</strong></p>
<ul>
<li>verteilungsfrei (erfordert keine Normalverteilung),</li>
<li>erkennt jegliche monotone Abhängigkeit,</li>
<li>wird durch Ausreißer kaum beeinträchtigt.</li>
</ul>
<p><strong>Nachteile:</strong></p>
<ul>
<li>gewisser Informationsverlust aufgrund der Rangbildung,</li>
<li>keine Informationen über die Art der Abhängigkeit,</li>
<li>keine direkte Beziehung zum Bestimmtheitsmaß.</li>
</ul>
<p>Fazit: <span class="math inline">\(r_s\)</span> ist dennoch sehr empfehlenswert!</p>
</section>
<section id="korrelationskoeffizienten-in-r" class="slide level2">
<h2>Korrelationskoeffizienten in <strong>R</strong></h2>
<ul>
<li>Pearson’s Produkt-Moment-Korrelationskoeffizient</li>
<li>Spearman’s Rangkorrelationskoeffizient</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>,  <span class="dv">9</span>)</span>
<span id="cb57-2"><a aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">11</span>)</span>
<span id="cb57-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(x, y, <span class="at">method=</span><span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  x and y
t = 7.969, df = 4, p-value = 0.001344
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.7439930 0.9968284
sample estimates:
      cor 
0.9699203 </code></pre>
</div>
</div>
<p>Wenn Linearität oder Normalität der Residuen zweifelhaft sind, verwende eine Rangkorrelation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(x, y, <span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  x and y
S = 2, p-value = 0.01667
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.9428571 </code></pre>
</div>
</div>
</section>
<section id="problemfälle" class="slide level2">
<h2>Problemfälle</h2>

<img data-src="05-classtests_files/figure-revealjs/cor-violations-1.png" width="576" class="r-stretch"></section>
<section id="ausblick-mehr-als-zwei-unabhängige-variablen" class="slide level2">
<h2>Ausblick: Mehr als zwei unabhängige Variablen</h2>
<p><br></p>
<p><strong>Multiple Korrelation</strong></p>
<ul>
<li><span class="blue">Beispiel:</span> Chl-a=<span class="math inline">\(f(x_1, x_2, x_3, \dots)\)</span>, wobei <span class="math inline">\(x_i\)</span> = Biomasse der <span class="math inline">\(i\)</span>-ten Phytoplanktonart.</li>
<li>multipler Korrelationskoeffizient</li>
<li>partieller Korrelationskoeffizient</li>
<li>Attraktive Methode <span class="math inline">\(\leftrightarrow\)</span>, aber in der Praxis schwierig:
<ul>
<li>„unabhängige“ Variablen können miteinander korrelieren (Multikollinearität)<br> <span class="math inline">\(\Rightarrow\)</span> Verzerrung des Vielfachen <span class="math inline">\(r\)</span>.</li>
<li>Nichtlinearitäten sind noch schwieriger zu handhaben als im Fall von zwei Stichproben.</li>
</ul></li>
</ul>
<p><strong>Empfehlung:</strong></p>
<ul>
<li>Verwende multivariate Methoden (NMDS, PCA, …) für einen ersten Überblick,</li>
<li>Wende die multiple Regression mit Sorgfalt an und nutze Prozesswissen.</li>
</ul>
</section>
<section id="literatur" class="slide level2 smaller scrollable">
<h2>Literatur</h2>
<p><br></p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-hubbard_alphabet_2004" class="csl-entry" role="listitem">
Hubbard, R. (2004). Alphabet soup: Blurring the distinctions between p’s and a’s in psychological research. <em>Theory &amp; Psychology</em>, <em>14</em>(3), 295–327. <a href="https://doi.org/10.1177/0959354304043638">https://doi.org/10.1177/0959354304043638</a>
</div>
<div id="ref-zimmerman_note_2004" class="csl-entry" role="listitem">
Zimmerman, D. W. (2004). A note on preliminary tests of equality of variances. <em>British Journal of Mathematical and Statistical Psychology</em>, <em>57</em>(1), 173–181. <a href="https://doi.org/10.1348/000711004849222">https://doi.org/10.1348/000711004849222</a>
</div>
</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><span style="color: white; font-size: small; font-weight:400; float: right; margin-top: 40px; margin-right: 4%;"> <a href="../">🏠 Home</a> </span></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>